# Tensors 

In [1]:
import torch

## zeros()

In [2]:
w = torch.zeros(4,3)
w

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## size() and shape

In [3]:
w.size()

torch.Size([4, 3])

In [4]:
w.shape

torch.Size([4, 3])

## randn() and randn_like()

In [5]:
w = torch.randn(4,3)
w

tensor([[ 0.7940, -0.4206,  1.7086],
        [ 0.5720, -0.1468,  0.4387],
        [ 1.1364,  1.7394, -0.8475],
        [-0.6303,  0.8876,  0.0521]])

In [6]:
t = torch.randn_like(w)
t

tensor([[-0.6759, -0.1195, -1.2308],
        [-0.3452,  0.4011,  1.6830],
        [ 1.3002, -0.6611, -0.0144],
        [-0.8219,  2.0304,  0.7778]])

## fill_()

In [7]:
w.fill_(1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## view()

In [8]:
w

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
t = w.view(3,4)
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
w.view(3,-1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## numpy()

In [11]:
w.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [13]:
type(w.numpy())

numpy.ndarray